# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d85b972f8ac225c9b60895de4d6fca2dff81bb29215739849f3568377a8bcf866393db4fb62e97ea6a0fb874c6b4d2b4c11fa42a8530d524c20795c42ceb84

test:
  secret_key_base: f8442c7477269696fdf6657317f8c999b781c91bd948051358aed5468b297be216af99d28c7f9eb02a6ac6040876cc6a1700ded5e4a2a39b96611825b2de590c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
